import { Footer } from "@/components/footer";
import { ChakraProvider } from "@chakra-ui/react";
import { Component } from "react";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

// app/layout.tsx
import { Providers } from "./providers";
import Script from "next/script";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          {children}
          <Footer />
        </Providers>
      </body>
      <Script
        type="text/javascript"
        src="//dapi.kakao.com/v2/maps/sdk.js?appkey=a3c09a99530dacbdfd899664125ed428&libraries=services,clusterer&autoload=false"
      ></Script>
    </html>
  );
}
