/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Kf1JBsy77cC
 */
import { CardTitle, Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { useRouter } from "next/router";

export function ColorfulMenu2() {
  const router = useRouter();
  return (
    <div className="flex flex-col h-screen p-4 bg-[#ffffff]">
      <header className="flex justify-center mb-10">
        <h1 className="text-4xl font-bold text-center">Welcome!</h1>
      </header>
      <main className="flex-grow grid grid-cols-2 gap-6">
        <Card className="flex flex-col items-center bg-gradient-to-r from-green-400 to-blue-500 text-white rounded-xl shadow-lg">
          <DumbbellIcon className="w-12 h-12 mb-2" />
          <CardTitle className="text-xl">시설 예약</CardTitle>
          <Button
            className="mt-auto p-2 bg-white text-blue-500 rounded-xl"
            variant="outline"
            onClick={() => {
              //GymReservation으로 route
              router.push("/gym");
            }}
          >
            Reserve Now
          </Button>
        </Card>
        <Card className="flex flex-col items-center bg-gradient-to-r from-red-400 to-yellow-500 text-white rounded-xl shadow-lg">
          <TicketIcon className="w-12 h-12 mb-2" />
          <CardTitle className="text-xl">Concert Tickets</CardTitle>
          <Button
            className="mt-auto p-2 bg-white text-red-500 rounded-xl"
            variant="outline"
          >
            Buy Now
          </Button>
        </Card>
        <Card className="flex flex-col items-center bg-gradient-to-r from-blue-400 to-pink-500 text-white rounded-xl shadow-lg">
          <PlaneIcon className="w-12 h-12 mb-2" />
          <CardTitle className="text-xl">Travel Reservation</CardTitle>
          <Button
            className="mt-auto p-2 bg-white text-blue-500 rounded-xl"
            variant="outline"
          >
            Book Now
          </Button>
        </Card>
        <Card className="flex flex-col items-center bg-gradient-to-r from-purple-400 to-indigo-500 text-white rounded-xl shadow-lg">
          <MoreHorizontalIcon className="w-12 h-12 mb-2" />
          <CardTitle className="text-xl">More</CardTitle>
          <Button
            className="mt-auto p-2 bg-white text-purple-500 rounded-xl"
            variant="outline"
          >
            Explore
          </Button>
        </Card>
      </main>
      <footer className="mt-10">
        <Button className="w-full p-4 rounded-xl bg-gray-800 text-white">
          Profile
        </Button>
      </footer>
    </div>
  );
}

function TicketIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M2 9a3 3 0 0 1 0 6v2a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-2a3 3 0 0 1 0-6V7a2 2 0 0 0-2-2H4a2 2 0 0 0-2 2Z" />
      <path d="M13 5v2" />
      <path d="M13 17v2" />
      <path d="M13 11v2" />
    </svg>
  );
}

function PlaneIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M17.8 19.2 16 11l3.5-3.5C21 6 21.5 4 21 3c-1-.5-3 0-4.5 1.5L13 8 4.8 6.2c-.5-.1-.9.1-1.1.5l-.3.5c-.2.5-.1 1 .3 1.3L9 12l-2 3H4l-1 1 3 2 2 3 1-1v-3l3-2 3.5 5.3c.3.4.8.5 1.3.3l.5-.2c.4-.3.6-.7.5-1.2z" />
    </svg>
  );
}

function MoreHorizontalIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="1" />
      <circle cx="19" cy="12" r="1" />
      <circle cx="5" cy="12" r="1" />
    </svg>
  );
}

function DumbbellIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m6.5 6.5 11 11" />
      <path d="m21 21-1-1" />
      <path d="m3 3 1 1" />
      <path d="m18 22 4-4" />
      <path d="m2 6 4-4" />
      <path d="m3 10 7-7" />
      <path d="m14 21 7-7" />
    </svg>
  );
}
