/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/P3XrjaMKlOl
 */
import { useRouter } from "next/router";
import { HStack, Text } from "@chakra-ui/react";
import Image from "next/image";
import { JSX, SVGProps } from "react";

export function GymReservation() {
  const router = useRouter();
  return (
    <div className="mx-auto">
      <div
        className="bg-[#00BFA5] text-center h-[50%] py-[150px]"
        onClick={() => {
          router.push("/gym/place");
        }}
      >
        <HStack justifyContent={"center"}>
          <Image src="/images/place.png" alt="이미지" width={60} height={60} />
        </HStack>
        <Text fontSize={40}>장소 선택</Text>
      </div>
      <div
        className="bg-[#EEEEEE] p-4 text-center h-[100%] py-[150px]"
        onClick={() => {
          router.push("/gym/time");
        }}
      >
        <HStack justifyContent={"center"}>
          <Image
            src="/images/calendar.png"
            alt="이미지"
            width={60}
            height={60}
          />
        </HStack>
        <Text fontSize={40}>시간 선택</Text>
      </div>
    </div>
  );
}

export function LocateIcon(
  props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>
) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="2" x2="5" y1="12" y2="12" />
      <line x1="19" x2="22" y1="12" y2="12" />
      <line x1="12" x2="12" y1="2" y2="5" />
      <line x1="12" x2="12" y1="19" y2="22" />
      <circle cx="12" cy="12" r="7" />
    </svg>
  );
}
